server {
  listen 80;
  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri $uri/ =404;
  }

  # Endpoint para a demo: mostra QUEM respondeu (nome do container/pod)
  location /whoami {
    default_type text/plain;
    return 200 "Servido por: $hostname\n";
  }

  # Encaminha os pedidos /api/... para o container/serviço "api"
  location /api/ {
    proxy_pass http://api:3000/api/;
  }
}
