apiVersion: v1
kind: Service
metadata:
  name: api          # tem de se chamar "api": é o nome usado no proxy_pass do nginx
spec:
  selector:
    app: api
  ports:
    - port: 3000
      targetPort: 3000
