apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          # Troca TEU-UTILIZADOR/NOME-DO-REPO (tudo em minúsculas)
          image: ghcr.io/mcarmo88/cicd-web-docker-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
