apiVersion: apps/v1
kind: Deployment
metadata:
  name: painel
spec:
  replicas: 3
  selector:
    matchLabels:
      app: painel
  template:
    metadata:
      labels:
        app: painel
    spec:
      containers:
        - name: painel
          image: ghcr.io/mcarmo88/cicd-web-docker:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80