apiVersion: v1
kind: Service
metadata:
  name: painel
spec:
  type: LoadBalancer     # no Docker Desktop fica acessível em localhost
  selector:
    app: painel
  ports:
    - port: 8090
      targetPort: 80
